name: Prerelease

on:
  push:
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install
      - name: Check pre-release state
        run: |
          if [ -f ./.changeset/pre.json ]; then
              pnpm changeset pre exit
          fi


      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          commit: "chore: update versions"
          title: "Release: new versions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
